### ISSUE TITLE
I can't see the applications in the remote card...

### ISSUE THREAD

**Issue by remyscherer** [marrobHD/tv-card#33]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** v.0.2.0

**Last working release (if known):**

**Browser and Operating System:** Chrome on Chromebook and in the homeassistant app on Android...

**Description of problem:**
I can't see the applications that I added. Maybe something is missing in the documentation or my code? 
I use this YAML: 

```
type: custom:tv-card
entity: media_player.fernseher
name: Fernseher
tv: true
power:
  service: script.fernbedienung_tv
  service_data:
    key: POWER
volume_up:
  service: script.fernbedienung_tv
  service_data:
    key: VOLUP
volume_down:
  service: script.fernbedienung_tv
  service_data:
    key: VOLDOWN
volume_mute:
  service: script.fernbedienung_tv
  service_data:
    key: MUTE
select:
  service: script.fernbedienung_tv
  service_data:
    key: ENTER
up:
  service: script.fernbedienung_tv
  service_data:
    key: UP
left:
  service: script.fernbedienung_tv
  service_data:
    key: LEFT
down:
  service: script.fernbedienung_tv
  service_data:
    key: DOWN
right:
  service: script.fernbedienung_tv
  service_data:
    key: RIGHT
applications:
  netflix:
    icon: mdi:netflix
    service: media_player.select_source
    service_data:
      entity_id: media_player.fernseher
      source: Netflix
  prime_video:
    icon: mdi:message-video
    service: media_player.select_source
    service_data:
      entity_id: media_player.fernseher
      source: Prime Video
  youtube:
    icon: mdi:youtube
    service: media_player.select_source
    service_data:
      entity_id: media_player.fernseher
      source: Youtube
```

Thanks for your help!
